"""Concrete production bindings used by the native wheel pure self-test."""

from __future__ import annotations

import types

import wheel_lib.native_wheel_publication as native_wheel_publication
from wheel_lib.native_wheel_macho import assert_clean_closure, assert_packaged_library_closure, copy_and_rewrite_closure
from wheel_lib.native_wheel_profile import FERRUM_RDKIT_PROFILE, RDKIT_CLOSURE_LIBRARY_INSTALL_NAMES
from wheel_lib.native_wheel_receipt import sha256
from wheel_lib.native_wheel_builder_adapter import validate_rdkit_configuration, validate_resolved_rdkit_configuration
from wheel_lib.native_wheel_builder_commands import command_publish_publication
from wheel_lib.native_wheel_builder_model import ADAPTER_ABI_VERSION, ADAPTER_NAME, BUNDLE_MANIFEST_NAME, BUNDLE_SCHEMA, FERRUM_SOURCE_CLOSURE_EXCLUDED_DIRECTORIES, FERRUM_SOURCE_CLOSURE_SCHEMA, FERRUM_WORKTREE_SOURCE_CLOSURE_EXCLUDED_DIRECTORIES, FERRUM_WORKTREE_SOURCE_CLOSURE_EXCLUDED_SUFFIXES, FERRUM_WORKTREE_SOURCE_CLOSURE_SCHEMA, MACHINE_RESULT_SCHEMA, NativeBuildError, REPO_ROOT, emit_artifact_result, engine_bundle_manifest, engine_bundle_path, executable_bundle_target, ferrum_source_closure, ferrum_worktree_source_closure, output_path, require_matching_worktree_source_closure, validate_build_receipt, validate_materialized_source, validate_publication_candidate, validate_publication_engine_bundle
from wheel_lib.native_wheel_builder_sources import HttpsOnlyRedirectHandler, archive_root_for_build, download_verified_archive, managed_source_archive_cache_root, materialized_archive_path, minimal_rdkit_options, provision_managed_source_archive_cache, publish_native_input_manifest, rdkit_layout_from_output_root, safe_extract, safe_extract_zip, safe_extract_zip_members, stage_rdkit_inputs, validate_wheel_members, verified_archive
from wheel_lib.native_wheel_builder_wheel import audit_wheel_closure, build_engine_bundle
from wheel_lib.native_wheel_packaging import stage_python_project


def production_bindings() -> types.SimpleNamespace:
	"""Return only the concrete production functions exercised by pure fixtures."""
	return types.SimpleNamespace(
		ADAPTER_ABI_VERSION=ADAPTER_ABI_VERSION,
		ADAPTER_NAME=ADAPTER_NAME,
		BUNDLE_MANIFEST_NAME=BUNDLE_MANIFEST_NAME,
		BUNDLE_SCHEMA=BUNDLE_SCHEMA,
		FERRUM_RDKIT_PROFILE=FERRUM_RDKIT_PROFILE,
		FERRUM_SOURCE_CLOSURE_EXCLUDED_DIRECTORIES=FERRUM_SOURCE_CLOSURE_EXCLUDED_DIRECTORIES,
		FERRUM_SOURCE_CLOSURE_SCHEMA=FERRUM_SOURCE_CLOSURE_SCHEMA,
		FERRUM_WORKTREE_SOURCE_CLOSURE_EXCLUDED_DIRECTORIES=FERRUM_WORKTREE_SOURCE_CLOSURE_EXCLUDED_DIRECTORIES,
		FERRUM_WORKTREE_SOURCE_CLOSURE_EXCLUDED_SUFFIXES=FERRUM_WORKTREE_SOURCE_CLOSURE_EXCLUDED_SUFFIXES,
		FERRUM_WORKTREE_SOURCE_CLOSURE_SCHEMA=FERRUM_WORKTREE_SOURCE_CLOSURE_SCHEMA,
		HttpsOnlyRedirectHandler=HttpsOnlyRedirectHandler,
		MACHINE_RESULT_SCHEMA=MACHINE_RESULT_SCHEMA,
		NativeBuildError=NativeBuildError,
		RDKIT_CLOSURE_LIBRARY_INSTALL_NAMES=RDKIT_CLOSURE_LIBRARY_INSTALL_NAMES,
		REPO_ROOT=REPO_ROOT,
		archive_root_for_build=archive_root_for_build,
		assert_clean_closure=assert_clean_closure,
		assert_packaged_library_closure=assert_packaged_library_closure,
		audit_wheel_closure=audit_wheel_closure,
		build_engine_bundle=build_engine_bundle,
		command_publish_publication=command_publish_publication,
		copy_and_rewrite_closure=copy_and_rewrite_closure,
		download_verified_archive=download_verified_archive,
		emit_artifact_result=emit_artifact_result,
		engine_bundle_manifest=engine_bundle_manifest,
		engine_bundle_path=engine_bundle_path,
		executable_bundle_target=executable_bundle_target,
		ferrum_source_closure=ferrum_source_closure,
		ferrum_worktree_source_closure=ferrum_worktree_source_closure,
		managed_source_archive_cache_root=managed_source_archive_cache_root,
		materialized_archive_path=materialized_archive_path,
		minimal_rdkit_options=minimal_rdkit_options,
		native_wheel_publication=native_wheel_publication,
		output_path=output_path,
		provision_managed_source_archive_cache=provision_managed_source_archive_cache,
		publish_native_input_manifest=publish_native_input_manifest,
		rdkit_layout_from_output_root=rdkit_layout_from_output_root,
		require_matching_worktree_source_closure=require_matching_worktree_source_closure,
		safe_extract=safe_extract,
		safe_extract_zip=safe_extract_zip,
		safe_extract_zip_members=safe_extract_zip_members,
		sha256=sha256,
		stage_python_project=stage_python_project,
		stage_rdkit_inputs=stage_rdkit_inputs,
		validate_build_receipt=validate_build_receipt,
		validate_materialized_source=validate_materialized_source,
		validate_publication_candidate=validate_publication_candidate,
		validate_publication_engine_bundle=validate_publication_engine_bundle,
		validate_rdkit_configuration=validate_rdkit_configuration,
		validate_resolved_rdkit_configuration=validate_resolved_rdkit_configuration,
		validate_wheel_members=validate_wheel_members,
		verified_archive=verified_archive,
	)
