//! Schema generation for the frozen protocol DTO contract.

use schemars::SchemaGenerator;

use super::dto::{
    DocumentAtomOxidationObserveRequestV1, DocumentMoleculeHydrogenMaterializationRequestV1,
    DocumentSmartsQueryRequestV1, OperationProtocolEnvelopeV1, OperationProtocolErrorResponseV1,
    OperationProtocolRequestV1, OperationProtocolResponseV1,
};

/// Produce the generated V1 schema document from the authoritative Rust DTOs.
#[must_use]
pub fn generated_operation_protocol_schema_v1() -> serde_json::Value {
    let mut generator = SchemaGenerator::default();
    let request = generator.subschema_for::<OperationProtocolRequestV1>();
    let success_response = generator.subschema_for::<OperationProtocolResponseV1>();
    let error_response = generator.subschema_for::<OperationProtocolErrorResponseV1>();
    let document_smarts_query_request = generator.subschema_for::<DocumentSmartsQueryRequestV1>();
    let document_atom_oxidation_observe_request =
        generator.subschema_for::<DocumentAtomOxidationObserveRequestV1>();
    let document_molecule_hydrogen_materialization_request =
        generator.subschema_for::<DocumentMoleculeHydrogenMaterializationRequestV1>();
    let mut root = generator.into_root_schema_for::<OperationProtocolEnvelopeV1>();
    root.insert(
        "title".to_owned(),
        serde_json::Value::String("Ferrum operation protocol V1".to_owned()),
    );
    root.insert(
        "x-ferrum-roots".to_owned(),
        serde_json::json!({
            "request": request,
            "success_response": success_response,
            "error_response": error_response,
            "document_smarts_query_request": document_smarts_query_request,
            "document_atom_oxidation_observe_request": document_atom_oxidation_observe_request,
            "document_molecule_hydrogen_materialization_request": document_molecule_hydrogen_materialization_request,
        }),
    );
    root.into()
}

/// Return the checked-in schema generated by [`generated_operation_protocol_schema_v1`].
#[must_use]
pub const fn operation_protocol_schema_v1() -> &'static str {
    include_str!("../../protocol/ferrum-operation-v1.schema.json")
}
