//! Private Rust projection of the public Ferrum-Chem adapter header.
//!
//! `build.rs` reads the C header and emits these constants so the wire contract
//! has one numeric authority. The public crate facade intentionally re-exports
//! only the ABI version needed by callers that load an adapter.

mod generated {
    include!(concat!(env!("OUT_DIR"), "/adapter_wire_constants.rs"));
}

/// ABI version required by [`crate::NativeChemEngine`].
pub const ADAPTER_ABI_VERSION: u32 = generated::ADAPTER_ABI_VERSION;

pub(crate) use generated::{
    FERRUM_CHEM_ALL_KNOWN_CAPABILITIES, FERRUM_CHEM_BOND_DIRECTION_BEGINDASH,
    FERRUM_CHEM_BOND_DIRECTION_BEGINWEDGE, FERRUM_CHEM_BOND_DIRECTION_ENDDOWNRIGHT,
    FERRUM_CHEM_BOND_DIRECTION_ENDUPRIGHT, FERRUM_CHEM_BOND_DIRECTION_NONE,
    FERRUM_CHEM_BOND_DIRECTION_OTHER, FERRUM_CHEM_BOND_STEREO_ANY, FERRUM_CHEM_BOND_STEREO_CIS,
    FERRUM_CHEM_BOND_STEREO_E, FERRUM_CHEM_BOND_STEREO_NONE, FERRUM_CHEM_BOND_STEREO_OTHER,
    FERRUM_CHEM_BOND_STEREO_TRANS, FERRUM_CHEM_BOND_STEREO_Z, FERRUM_CHEM_CALL_ALLOCATION_FAILURE,
    FERRUM_CHEM_CAPABILITY_COMPOSITION, FERRUM_CHEM_CAPABILITY_GENERATE_2D,
    FERRUM_CHEM_CAPABILITY_INCHI, FERRUM_CHEM_CAPABILITY_KEKULIZE, FERRUM_CHEM_CAPABILITY_MOLFILE,
    FERRUM_CHEM_CAPABILITY_MOLFILE_READ, FERRUM_CHEM_CAPABILITY_MOLFILE_TITLE,
    FERRUM_CHEM_CAPABILITY_SDF_READ, FERRUM_CHEM_CAPABILITY_SDF_WRITE,
    FERRUM_CHEM_CAPABILITY_SMARTS, FERRUM_CHEM_CAPABILITY_SMARTS_MATCH,
    FERRUM_CHEM_CAPABILITY_SMILES_MOLECULE, FERRUM_CHEM_CAPABILITY_SMILES_WRITE,
    FERRUM_CHEM_CHIRAL_OTHER, FERRUM_CHEM_CHIRAL_TETRAHEDRAL_CCW,
    FERRUM_CHEM_CHIRAL_TETRAHEDRAL_CW, FERRUM_CHEM_CHIRAL_UNSPECIFIED,
    FERRUM_CHEM_COMPOSITION_ENTRY_BYTES, FERRUM_CHEM_COMPOSITION_FLAGS_NONE,
    FERRUM_CHEM_COMPOSITION_MAX_DETAIL_BYTES, FERRUM_CHEM_COMPOSITION_MAX_FORMULA_BYTES,
    FERRUM_CHEM_COMPOSITION_RESPONSE_HEADER_BYTES, FERRUM_CHEM_COMPOSITION_WIRE_VERSION,
    FERRUM_CHEM_COORDINATE_BYTES, FERRUM_CHEM_GRAPH_ATOM_BYTES, FERRUM_CHEM_GRAPH_BOND_BYTES,
    FERRUM_CHEM_GRAPH_FLAGS_NONE, FERRUM_CHEM_GRAPH_REQUEST_HEADER_BYTES,
    FERRUM_CHEM_GRAPH_WIRE_VERSION, FERRUM_CHEM_INCHI_FLAGS_NONE, FERRUM_CHEM_INCHI_KEY_BYTES,
    FERRUM_CHEM_INCHI_MAX_BYTES, FERRUM_CHEM_INCHI_MODE_FIXED_HYDROGEN,
    FERRUM_CHEM_INCHI_MODE_STANDARD, FERRUM_CHEM_INCHI_REQUEST_HEADER_BYTES,
    FERRUM_CHEM_INCHI_WIRE_VERSION, FERRUM_CHEM_KEKULIZE_ATOM_BYTES,
    FERRUM_CHEM_KEKULIZE_BOND_BYTES, FERRUM_CHEM_KEKULIZE_BOND_TYPE_AROMATIC,
    FERRUM_CHEM_KEKULIZE_BOND_TYPE_DOUBLE, FERRUM_CHEM_KEKULIZE_BOND_TYPE_QUADRUPLE,
    FERRUM_CHEM_KEKULIZE_BOND_TYPE_SINGLE, FERRUM_CHEM_KEKULIZE_BOND_TYPE_TRIPLE,
    FERRUM_CHEM_KEKULIZE_BOND_TYPE_UNSPECIFIED, FERRUM_CHEM_KEKULIZE_FACT_EXPLICIT_HYDROGENS,
    FERRUM_CHEM_KEKULIZE_FACT_FORMAL_CHARGE, FERRUM_CHEM_KEKULIZE_FACT_ISOTOPE,
    FERRUM_CHEM_KEKULIZE_MAX_ATOMS, FERRUM_CHEM_KEKULIZE_MAX_BACKTRACKS,
    FERRUM_CHEM_KEKULIZE_MAX_BONDS, FERRUM_CHEM_KEKULIZE_MAX_DETAIL_BYTES,
    FERRUM_CHEM_KEKULIZE_OPTION_CANONICAL, FERRUM_CHEM_KEKULIZE_OPTION_CLEAR_AROMATIC_FLAGS,
    FERRUM_CHEM_KEKULIZE_REQUEST_HEADER_BYTES, FERRUM_CHEM_KEKULIZE_RESPONSE_HEADER_BYTES,
    FERRUM_CHEM_KEKULIZE_WIRE_VERSION, FERRUM_CHEM_MAX_RESPONSE_BYTES,
    FERRUM_CHEM_MOLBLOCK_FLAGS_NONE, FERRUM_CHEM_MOLBLOCK_FORMAT_V2000,
    FERRUM_CHEM_MOLBLOCK_FORMAT_V3000, FERRUM_CHEM_MOLBLOCK_REQUEST_HEADER_BYTES,
    FERRUM_CHEM_MOLBLOCK_WIRE_VERSION, FERRUM_CHEM_MOLECULE_ATOM_BYTES,
    FERRUM_CHEM_MOLECULE_BOND_BYTES, FERRUM_CHEM_MOLECULE_FLAGS_NONE,
    FERRUM_CHEM_MOLECULE_RESERVED, FERRUM_CHEM_MOLECULE_RESPONSE_HEADER_BYTES,
    FERRUM_CHEM_MOLECULE_STEREO_REFERENCE_NONE, FERRUM_CHEM_MOLECULE_WIRE_VERSION,
    FERRUM_CHEM_RESULT_DEPICTION_FAILURE, FERRUM_CHEM_RESULT_INTERNAL_FAILURE,
    FERRUM_CHEM_RESULT_INVALID_MOLECULE, FERRUM_CHEM_RESULT_MALFORMED_REQUEST,
    FERRUM_CHEM_RESULT_OK, FERRUM_CHEM_RESULT_RESOURCE_LIMIT,
    FERRUM_CHEM_RESULT_UNSUPPORTED_MOLECULE, FERRUM_CHEM_SDF_FLAGS_NONE,
    FERRUM_CHEM_SDF_MAX_PROPERTIES, FERRUM_CHEM_SDF_MAX_RECORDS,
    FERRUM_CHEM_SDF_PROPERTY_HEADER_BYTES, FERRUM_CHEM_SDF_RECORD_HEADER_BYTES,
    FERRUM_CHEM_SDF_REQUEST_HEADER_BYTES, FERRUM_CHEM_SDF_RESPONSE_HEADER_BYTES,
    FERRUM_CHEM_SDF_WIRE_VERSION, FERRUM_CHEM_SMARTS_MATCH_FLAG_TRUNCATED,
    FERRUM_CHEM_SMARTS_MATCH_MAX_MATRIX_CELLS, FERRUM_CHEM_SMARTS_MATCH_MAX_QUERY_BYTES,
    FERRUM_CHEM_SMARTS_MATCH_MAX_ROWS, FERRUM_CHEM_SMARTS_MATCH_REQUEST_HEADER_BYTES,
    FERRUM_CHEM_SMARTS_MATCH_RESPONSE_HEADER_BYTES, FERRUM_CHEM_SMARTS_MATCH_STATUS_INVALID_QUERY,
    FERRUM_CHEM_SMARTS_MATCH_STATUS_INVALID_REQUEST,
    FERRUM_CHEM_SMARTS_MATCH_STATUS_NATIVE_FAILURE, FERRUM_CHEM_SMARTS_MATCH_STATUS_OK,
    FERRUM_CHEM_SMARTS_MATCH_STATUS_RESOURCE_LIMITED,
    FERRUM_CHEM_SMARTS_MATCH_STATUS_UNSUPPORTED_TARGET, FERRUM_CHEM_SMARTS_MATCH_WIRE_VERSION,
    FERRUM_CHEM_SMILES_MAX_BYTES, FERRUM_CHEM_SMILES_WRITE_MAX_BYTES, FERRUM_CHEM_TEXT_FLAGS_NONE,
    FERRUM_CHEM_TEXT_RESPONSE_HEADER_BYTES, FERRUM_CHEM_TEXT_WIRE_VERSION,
    FERRUM_CHEM_TITLED_MOLBLOCK_REQUEST_HEADER_BYTES, FERRUM_CHEM_TITLED_MOLBLOCK_WIRE_VERSION,
};
