//! Stable, owned chemistry values at Ferrum's engine boundary.
//!
//! This crate intentionally knows neither CDML nor a native toolkit.  An engine
//! receives a validated [`MolGraph`] and returns a new one, keeping callers free
//! of foreign handles, borrowed buffers, and toolkit-specific representations.

mod adapter_contract;
mod composition;
mod element;
mod engine;
mod model;
mod native_engine;
mod sdf;

pub use crate::composition::{
    CompositionAggregationError, CompositionBuildError, CompositionElementKey, ElementCount,
    ElementMassPercentage, MoleculeComposition, MoleculeCompositionEntry,
};
pub use crate::engine::{
    ChemEngine, ChemistryError, InchiMode, KekulizeOptions, KekulizeOptionsError, MolblockVersion,
    UnavailableChemEngine,
};
pub use crate::model::{
    AtomChirality, AtomicNumber, BondDirection, BondOrder, BondStereo, Coordinates, MolAtom,
    MolBond, MolGraph, MolGraphError, Point2, SmilesMolecule,
};
pub use crate::native_engine::{
    INCHI_MAX_INPUT_BYTES, MOLBLOCK_MAX_INPUT_BYTES, NATIVE_SMILES_MAX_INPUT_BYTES,
    NATIVE_SMILES_MAX_OUTPUT_BYTES, NativeChemEngine, SDF_MAX_INPUT_BYTES, validate_inchi_input,
    validate_molblock_input, validate_molblock_title, validate_sdf_input, validate_smiles_input,
};
pub use crate::sdf::{ImportedSdfRecord, SdfError, SdfProperty, SdfRecord, compose_sdf_record};

pub use crate::adapter_contract::ADAPTER_ABI_VERSION;
pub(crate) use crate::adapter_contract::{
    FERRUM_CHEM_COMPOSITION_ENTRY_BYTES, FERRUM_CHEM_COMPOSITION_FLAGS_NONE,
    FERRUM_CHEM_COMPOSITION_MAX_DETAIL_BYTES, FERRUM_CHEM_COMPOSITION_MAX_FORMULA_BYTES,
    FERRUM_CHEM_COMPOSITION_RESPONSE_HEADER_BYTES, FERRUM_CHEM_COMPOSITION_WIRE_VERSION,
    FERRUM_CHEM_COORDINATE_BYTES, FERRUM_CHEM_GRAPH_ATOM_BYTES, FERRUM_CHEM_GRAPH_BOND_BYTES,
    FERRUM_CHEM_GRAPH_FLAGS_NONE, FERRUM_CHEM_GRAPH_REQUEST_HEADER_BYTES,
    FERRUM_CHEM_GRAPH_WIRE_VERSION, FERRUM_CHEM_INCHI_FLAGS_NONE, FERRUM_CHEM_INCHI_KEY_BYTES,
    FERRUM_CHEM_INCHI_MAX_BYTES, FERRUM_CHEM_INCHI_MODE_FIXED_HYDROGEN,
    FERRUM_CHEM_INCHI_MODE_STANDARD, FERRUM_CHEM_INCHI_REQUEST_HEADER_BYTES,
    FERRUM_CHEM_INCHI_WIRE_VERSION, FERRUM_CHEM_KEKULIZE_ATOM_BYTES,
    FERRUM_CHEM_KEKULIZE_BOND_BYTES, FERRUM_CHEM_KEKULIZE_BOND_TYPE_AROMATIC,
    FERRUM_CHEM_KEKULIZE_BOND_TYPE_DOUBLE, FERRUM_CHEM_KEKULIZE_BOND_TYPE_QUADRUPLE,
    FERRUM_CHEM_KEKULIZE_BOND_TYPE_SINGLE, FERRUM_CHEM_KEKULIZE_BOND_TYPE_TRIPLE,
    FERRUM_CHEM_KEKULIZE_BOND_TYPE_UNSPECIFIED, FERRUM_CHEM_KEKULIZE_FACT_EXPLICIT_HYDROGENS,
    FERRUM_CHEM_KEKULIZE_FACT_FORMAL_CHARGE, FERRUM_CHEM_KEKULIZE_FACT_ISOTOPE,
    FERRUM_CHEM_KEKULIZE_MAX_ATOMS, FERRUM_CHEM_KEKULIZE_MAX_BACKTRACKS,
    FERRUM_CHEM_KEKULIZE_MAX_BONDS, FERRUM_CHEM_KEKULIZE_MAX_DETAIL_BYTES,
    FERRUM_CHEM_KEKULIZE_OPTION_CANONICAL, FERRUM_CHEM_KEKULIZE_OPTION_CLEAR_AROMATIC_FLAGS,
    FERRUM_CHEM_KEKULIZE_REQUEST_HEADER_BYTES, FERRUM_CHEM_KEKULIZE_RESPONSE_HEADER_BYTES,
    FERRUM_CHEM_KEKULIZE_WIRE_VERSION, FERRUM_CHEM_MAX_RESPONSE_BYTES,
    FERRUM_CHEM_MOLBLOCK_FLAGS_NONE, FERRUM_CHEM_MOLBLOCK_FORMAT_V2000,
    FERRUM_CHEM_MOLBLOCK_FORMAT_V3000, FERRUM_CHEM_MOLBLOCK_REQUEST_HEADER_BYTES,
    FERRUM_CHEM_MOLBLOCK_WIRE_VERSION, FERRUM_CHEM_MOLECULE_ATOM_BYTES,
    FERRUM_CHEM_MOLECULE_BOND_BYTES, FERRUM_CHEM_MOLECULE_RESPONSE_HEADER_BYTES,
    FERRUM_CHEM_RESULT_DEPICTION_FAILURE, FERRUM_CHEM_RESULT_INTERNAL_FAILURE,
    FERRUM_CHEM_RESULT_INVALID_MOLECULE, FERRUM_CHEM_RESULT_MALFORMED_REQUEST,
    FERRUM_CHEM_RESULT_OK, FERRUM_CHEM_RESULT_RESOURCE_LIMIT,
    FERRUM_CHEM_RESULT_UNSUPPORTED_MOLECULE, FERRUM_CHEM_SDF_FLAGS_NONE,
    FERRUM_CHEM_SDF_MAX_PROPERTIES, FERRUM_CHEM_SDF_MAX_RECORDS,
    FERRUM_CHEM_SDF_PROPERTY_HEADER_BYTES, FERRUM_CHEM_SDF_RECORD_HEADER_BYTES,
    FERRUM_CHEM_SDF_REQUEST_HEADER_BYTES, FERRUM_CHEM_SDF_RESPONSE_HEADER_BYTES,
    FERRUM_CHEM_SDF_WIRE_VERSION, FERRUM_CHEM_SMILES_MAX_BYTES, FERRUM_CHEM_SMILES_WRITE_MAX_BYTES,
    FERRUM_CHEM_TEXT_FLAGS_NONE, FERRUM_CHEM_TEXT_RESPONSE_HEADER_BYTES,
    FERRUM_CHEM_TEXT_WIRE_VERSION, FERRUM_CHEM_TITLED_MOLBLOCK_REQUEST_HEADER_BYTES,
    FERRUM_CHEM_TITLED_MOLBLOCK_WIRE_VERSION,
};
