"""Compatibility facade for legacy Qt undo command imports.

The persistent backend session owns revisions and durable history.  These
QUndoCommand classes are disposable Qt projection commands only.
"""

import ferrum_qt.undo.fragment_commands
import ferrum_qt.undo.graphics_lifecycle
import ferrum_qt.undo.molecule_commands
import ferrum_qt.undo.presentation_commands
import ferrum_qt.undo.property_commands
import ferrum_qt.undo.structure_commands

AddFragmentCommand = ferrum_qt.undo.fragment_commands.AddFragmentCommand
RemoveFragmentCommand = ferrum_qt.undo.fragment_commands.RemoveFragmentCommand
_dispose_command_graphics = ferrum_qt.undo.graphics_lifecycle._dispose_command_graphics
dispose_undo_stack_graphics = ferrum_qt.undo.graphics_lifecycle.dispose_undo_stack_graphics
AddMoleculeCommand = ferrum_qt.undo.molecule_commands.AddMoleculeCommand
RemoveMoleculeCommand = ferrum_qt.undo.molecule_commands.RemoveMoleculeCommand
AddAtomMarkCommand = ferrum_qt.undo.presentation_commands.AddAtomMarkCommand
AddPresentationObjectCommand = ferrum_qt.undo.presentation_commands.AddPresentationObjectCommand
MovePresentationObjectsCommand = ferrum_qt.undo.presentation_commands.MovePresentationObjectsCommand
RemoveAtomMarkCommand = ferrum_qt.undo.presentation_commands.RemoveAtomMarkCommand
RemovePresentationObjectCommand = ferrum_qt.undo.presentation_commands.RemovePresentationObjectCommand
ReorderDocumentObjectsCommand = ferrum_qt.undo.presentation_commands.ReorderDocumentObjectsCommand
TransformGeometryCommand = ferrum_qt.undo.presentation_commands.TransformGeometryCommand
ChangePropertyCommand = ferrum_qt.undo.property_commands.ChangePropertyCommand
AddAtomCommand = ferrum_qt.undo.structure_commands.AddAtomCommand
AddBondCommand = ferrum_qt.undo.structure_commands.AddBondCommand
MoveAtomsCommand = ferrum_qt.undo.structure_commands.MoveAtomsCommand
RemoveAtomCommand = ferrum_qt.undo.structure_commands.RemoveAtomCommand
RemoveBondCommand = ferrum_qt.undo.structure_commands.RemoveBondCommand
