//! Context-qualified CDML record classifications.

/// Every CDML record class assigned a typed representation by the context table.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum TypedClass {
    Cdml,
    Info,
    AuthorProgram,
    Author,
    Note,
    Metadata,
    MetadataDocument,
    Standard,
    StandardBond,
    StandardArrow,
    StandardAtom,
    Paper,
    Viewport,
    Molecule,
    CanvasArrow,
    CanvasPlus,
    CanvasText,
    Rectangle,
    Square,
    Oval,
    Circle,
    Polygon,
    Polyline,
    Reaction,
    ReactionReactant,
    ReactionProduct,
    ReactionArrow,
    ReactionCondition,
    ReactionPlus,
    ExternalData,
    Atom,
    CompactGroup,
    Group,
    MoleculeText,
    Query,
    Bond,
    Template,
    Fragment,
    DisplayForm,
    UserData,
    FragmentName,
    FragmentBond,
    FragmentVertex,
    FragmentProperty,
    Point,
    Font,
    FormattedText,
    Mark,
}

impl TypedClass {
    /// Return the context-qualified stable class name used in diagnostics.
    #[must_use]
    pub fn name(self) -> &'static str {
        match self {
            Self::Cdml => "cdml",
            Self::Info => "cdml/info",
            Self::AuthorProgram => "info/author_program",
            Self::Author => "info/author",
            Self::Note => "info/note",
            Self::Metadata => "cdml/metadata",
            Self::MetadataDocument => "metadata/doc",
            Self::Standard => "cdml/standard",
            Self::StandardBond => "standard/bond",
            Self::StandardArrow => "standard/arrow",
            Self::StandardAtom => "standard/atom",
            Self::Paper => "cdml/paper",
            Self::Viewport => "cdml/viewport",
            Self::Molecule => "cdml/molecule",
            Self::CanvasArrow => "cdml/arrow",
            Self::CanvasPlus => "cdml/plus",
            Self::CanvasText => "cdml/text",
            Self::Rectangle => "cdml/rect",
            Self::Square => "cdml/square",
            Self::Oval => "cdml/oval",
            Self::Circle => "cdml/circle",
            Self::Polygon => "cdml/polygon",
            Self::Polyline => "cdml/polyline",
            Self::Reaction => "cdml/reaction",
            Self::ReactionReactant => "reaction/reactant",
            Self::ReactionProduct => "reaction/product",
            Self::ReactionArrow => "reaction/arrow",
            Self::ReactionCondition => "reaction/condition",
            Self::ReactionPlus => "reaction/plus",
            Self::ExternalData => "cdml/external-data",
            Self::Atom => "molecule/atom",
            Self::CompactGroup => "molecule/compact-group",
            Self::Group => "molecule/group",
            Self::MoleculeText => "molecule/text",
            Self::Query => "molecule/query",
            Self::Bond => "molecule/bond",
            Self::Template => "molecule/template",
            Self::Fragment => "molecule/fragment",
            Self::DisplayForm => "molecule/display-form",
            Self::UserData => "molecule/user-data",
            Self::FragmentName => "fragment/name",
            Self::FragmentBond => "fragment/bond",
            Self::FragmentVertex => "fragment/vertex",
            Self::FragmentProperty => "fragment/property",
            Self::Point => "shared/point",
            Self::Font => "shared/font",
            Self::FormattedText => "shared/ftext",
            Self::Mark => "atom/mark",
        }
    }
}
